[project]
name = "ceia-final-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Kevin Cajachuán",email = "kevincajachuan@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "ceia_final_project", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
